//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace ExampleProjectLib
{
	/// <summary>
	/// 一个游戏场景.....
	/// 
	/// 部分非实时游戏UI也可以算场景
	/// </summary>
	class GameMap : GameBehaviour
	{
		public static Dictionary<int, GameMap> Maps = new Dictionary<int, GameMap>();
		private GameMap ()
		{
		}

		public static GameMap Get(int mapId)
		{
			GameMap map;
			if (!Maps.TryGetValue(mapId, out map))
			{
				map = Maps[mapId] = new GameMap();
			}

			return map;
		}

		public override void Update()
		{

		}
	}
}

