//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Threading.Tasks;

namespace ExampleProjectLib
{
	class GateServices
	{
		GameActor _actor;
		public GateServices (GameActor actor)
		{
			_actor = actor;
		}

		public Task<PlayerSession> UserLogin()
		{
			var player = new Player(new PlayerData());
			var pSession = new PlayerSession(player);

			return null;
		}

		/// <summary>
		/// 返回，有多少怪物
		/// </summary>
		/// <param name="session">Session.</param>
		public GameMap OpenMap(PlayerSession session, int mapId)
		{
			return null;
		}

		public Task<bool> UserLogout(PlayerSession session)
		{
			return null;
		}
	}
}

