//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ExampleProjectLib
{
	public class PlayerSession
	{
		public Player Player {get; private set;}
        public string SessionToken { get; private set; }
		public PlayerSession (string sessionToken)
		{
		    SessionToken = sessionToken;
            Player = new Player(SessionToken, new PlayerEntity());
		}
	}
}

