//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ExampleProjectLib
{
    public enum PlayerState
    {
        UI,
        Level,
    }
	/// <summary>
	/// Rpc Send
	/// </summary>
	public class PlayerEntity
	{
		public int Uid;
		public int Hp;
		public int Attack;

	    public long Exp;
	    public PlayerState State;
	    public object StateArg; 
	}
}

