language: csharp
solution: src/cosmos.sln
mono:
  - latest
  - 3.12.0
install:
  - nuget restore src/cosmos.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/cosmos.sln
  #- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./release/CosmosTest.dll