//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Threading;

namespace Cosmos.Tool
{
    internal class CoroutineRunner
    {
        /// <summary>
        /// 25 frame every seconds
        /// 1000ms / 25ms = 40
        /// </summary>
        private static int HeartbeatMilliseconds = 40;

        private static CoroutineRunner Instance = new CoroutineRunner();
        private static LinkedList<Coroutine> _coroutines = new LinkedList<Coroutine>();
        private Thread _coroutineRunnerThread;
        private CoroutineRunner()
        {
            DoLoopTaskAsync();
        }

        void DoLoopTaskAsync()
        {
            _coroutineRunnerThread = new Thread(() =>
            {
                while (true)
                {
                    var node = _coroutines.First;
                    if (node != null)
                    {
                        do
                        {
                            var co = node.Value;
                            if (!co.MoveNext())
                            {
                                co.IsFinished = true;
                                var lastNode = node;
                                node = node.Next;
                                _coroutines.Remove(lastNode);
                            }
                            else
                            {
                                if (co.OnYield != null)
                                    co.OnYield(co.Current);

                                node = node.Next;
                            }

                        }
                        while (node != null);
                    }

                    Thread.Sleep(HeartbeatMilliseconds);
                }
            });
            _coroutineRunnerThread.Start();
        }

        /// <summary>
        /// Setup every yield interval time
        /// For examples,
        /// 25 times in 1s = 1000ms / 25 = 40ms (Default)
        /// </summary>
        /// <param name="ms"></param>
        public static void SetupHeartbeatMilliseconds(int ms)
        {
            HeartbeatMilliseconds = ms;
        }

        public static Coroutine Start(IEnumerator enumtor)
        {
            var co = new EnumtorCoroutine(enumtor);
            _coroutines.AddLast(co);
            return co;
        }
    }
}

