//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace ExampleProjectLib
{

	public class Character : MapObject
	{
		public int Hp;
		public int Attack;

		public Character ()
		{

		}

		public Skill CastSkill(Character target)
		{
			return new Skill(Attack, this, target);
		}
	}
}

